from pathlib import Path

ROOT = Path("app/src/main/java/com/devlinguistpro/mediatoolbox")
SCANNER = ROOT / "ScannerActivity.kt"
MAIN = ROOT / "MainActivity.kt"
QR = ROOT / "QrScannerActivity.kt"
GALLERY = ROOT / "GalleryActivity.kt"

def balanced_block(text, start):
    op = text.find("{", start)
    if op < 0: raise SystemExit("Could not find opening brace")
    depth = 0
    for i in range(op, len(text)):
        if text[i] == "{": depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0: return start, i + 1
    raise SystemExit("Unbalanced Kotlin block")

scanner = SCANNER.read_text(encoding="utf-8")
cap_start = scanner.find("@Composable\nprivate fun ScannerCapture(")
cap_end = scanner.find("\n@Composable", cap_start + 1)
if cap_start < 0 or cap_end < 0: raise SystemExit("ScannerCapture function boundary not found")
cap = scanner[cap_start:cap_end]

# Keep ScannerCapture structurally identical to the normal camera chrome:
# one shared controls row and one shared CAMERA/GALLERY navigation row.
# Preserve the camera preview and the existing PAGES preview destination.
bottom = "Column(\n            Modifier\n                .align(Alignment.BottomCenter)"
b = cap.find(bottom)
if b >= 0:
    a, e = balanced_block(cap, b)
    replacement = '''Column(
            Modifier
                .align(Alignment.BottomCenter)
                .fillMaxWidth()
                .background(ComposeColor.Black.copy(alpha = 0.82f))
                .navigationBarsPadding()
        ) {
            CameraSectionControls(
                mode = CameraSectionMode.SCAN,
                onModeSelected = { scannerModeAction(context, it) },
                onPrimaryAction = onCapture,
                onFlip = onFinish,
                onMore = { },
                primaryEnabled = true
            )
            CameraSectionBottomNavigation(cameraSelected = true, onCamera = onOpenCamera, onGallery = onOpenGallery)
        }'''
    cap = cap[:a] + replacement + cap[e:]
else:
    raise SystemExit("Scanner bottom control column not found")

scanner = scanner[:cap_start] + cap + scanner[cap_end:]
SCANNER.write_text(scanner, encoding="utf-8")

# Main -> Scanner/QR uses forward transition. Scanner/QR -> another section uses reverse.
main = MAIN.read_text(encoding="utf-8")
main = main.replace('overridePendingTransition(0, 0)', 'overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left)')
MAIN.write_text(main, encoding="utf-8")

scanner = SCANNER.read_text(encoding="utf-8")
scanner = scanner.replace('overridePendingTransition(0, 0)', 'overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)')
scanner = scanner.replace(
    'onOpenQr = { startActivity(Intent(this, QrScannerActivity::class.java)); overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right) }',
    'onOpenQr = { startActivity(Intent(this, QrScannerActivity::class.java)); overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left) }')
scanner = scanner.replace(
    'CameraSectionMode.PHOTO, CameraSectionMode.VIDEO -> context.startActivity(Intent(context, MainActivity::class.java).putExtras(cameraModeIntent(mode)))',
    'CameraSectionMode.PHOTO, CameraSectionMode.VIDEO -> { context.startActivity(Intent(context, MainActivity::class.java).putExtras(cameraModeIntent(mode))); (context as? ComponentActivity)?.overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right) }')
scanner = scanner.replace(
    'CameraSectionMode.QR -> context.startActivity(Intent(context, QrScannerActivity::class.java))',
    'CameraSectionMode.QR -> { context.startActivity(Intent(context, QrScannerActivity::class.java)); (context as? ComponentActivity)?.overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left) }')
SCANNER.write_text(scanner, encoding="utf-8")

qr = QR.read_text(encoding="utf-8")
qr = qr.replace('overridePendingTransition(0, 0)', 'overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)')
QR.write_text(qr, encoding="utf-8")

# Gallery pager is generated by its dedicated compile-safe finalizer.
exec(Path("tools/fix_gallery_pager.py").read_text(encoding="utf-8"), globals())

# Final source audit: verify the actual composable structures, not just markers.
scanner_final = SCANNER.read_text(encoding="utf-8")
cap_start = scanner_final.find("@Composable\nprivate fun ScannerCapture(")
cap_end = scanner_final.find("\n@Composable", cap_start + 1)
cap = scanner_final[cap_start:cap_end]
qr_final = QR.read_text(encoding="utf-8")
qr_start = qr_final.find("@Composable\nprivate fun QrScannerScreen(")
qr_end = qr_final.find("\n@Composable", qr_start + 1)
qr_cap = qr_final[qr_start:qr_end if qr_end >= 0 else len(qr_final)]
main_final = MAIN.read_text(encoding="utf-8")
gallery_final = GALLERY.read_text(encoding="utf-8")
checks = {
    "scanner shared controls": 'mode = CameraSectionMode.SCAN' in cap and 'CameraSectionBottomNavigation(' in cap and 'onFlip = onFinish' in cap,
    "scanner old controls removed": 'Text("Finish")' not in cap and 'LazyRow(' not in cap and 'Text("MORE"' not in cap,
    "scanner capture header removed": 'Text("Scanner", color = ComposeColor.White' not in cap and 'IconButton(onClick = onBack)' not in cap,
    "gallery interactive pager": 'Animatable' in gallery_final and 'swipeOffset' in gallery_final and 'animateTo' in gallery_final,
    "gallery adjacent media": 'AdjacentMedia(' in gallery_final and 'previousItem' in gallery_final and 'nextItem' in gallery_final,
    "gallery action row above media": '.zIndex(10f)' in gallery_final,
    "main forward slide": 'R.anim.slide_in_right' in main_final and 'R.anim.slide_out_left' in main_final,
    "qr reverse navigation": 'R.anim.slide_in_left' in qr_final and 'R.anim.slide_out_right' in qr_final,
}
for name, ok in checks.items(): print(("PASS " if ok else "FAIL ") + name)
failed = [name for name, ok in checks.items() if not ok]
if failed: raise SystemExit("FINAL UI AUDIT FAILED: " + "; ".join(failed))
print("Final gallery/scanner/QR layout audit passed.")
